spring:
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:runrun}
    username: ${POSTGRES_USER:runrun}
    password: ${POSTGRES_PASSWORD:runrun123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 2000ms
  mongodb:
    uri: mongodb://localhost:${MONGO_PORT:27017}/${MONGO_DB:runrun_chat}
springdoc:
  group-configs:
    - group: all
      paths-to-match: /**

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
  access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME_MS}
  refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME_MS}
server:
  port: 8080
file:
  upload-path: ${FILE_UPLOAD_PATH}
tmap:
  app-key: ${TMAP_APP_KEY}
  base-url: ${TMAP_BASE_URL}
